// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYthZ36_L7KGwnOGKGDLSgM7k-xYdDJG8',
    appId: '1:416045151692:web:7f5ab0027df5d737141969',
    messagingSenderId: '416045151692',
    projectId: 'recomendacao-filmes-b3326',
    authDomain: 'recomendacao-filmes-b3326.firebaseapp.com',
    databaseURL: 'https://recomendacao-filmes-b3326-default-rtdb.firebaseio.com',
    storageBucket: 'recomendacao-filmes-b3326.firebasestorage.app',
    measurementId: 'G-FHXW5NBPGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTRN30eIO1y13Of54jVXn93iWYg4adE4s',
    appId: '1:416045151692:android:e002f5a74d934e33141969',
    messagingSenderId: '416045151692',
    projectId: 'recomendacao-filmes-b3326',
    databaseURL: 'https://recomendacao-filmes-b3326-default-rtdb.firebaseio.com',
    storageBucket: 'recomendacao-filmes-b3326.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF5ypaq_--5FWEfvuDHIansbs82nTQ84Y',
    appId: '1:416045151692:ios:96ed8e94f0e6d463141969',
    messagingSenderId: '416045151692',
    projectId: 'recomendacao-filmes-b3326',
    databaseURL: 'https://recomendacao-filmes-b3326-default-rtdb.firebaseio.com',
    storageBucket: 'recomendacao-filmes-b3326.firebasestorage.app',
    iosBundleId: 'com.example.recomendacaoFilme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF5ypaq_--5FWEfvuDHIansbs82nTQ84Y',
    appId: '1:416045151692:ios:96ed8e94f0e6d463141969',
    messagingSenderId: '416045151692',
    projectId: 'recomendacao-filmes-b3326',
    databaseURL: 'https://recomendacao-filmes-b3326-default-rtdb.firebaseio.com',
    storageBucket: 'recomendacao-filmes-b3326.firebasestorage.app',
    iosBundleId: 'com.example.recomendacaoFilme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYthZ36_L7KGwnOGKGDLSgM7k-xYdDJG8',
    appId: '1:416045151692:web:b49f1a20d6aad113141969',
    messagingSenderId: '416045151692',
    projectId: 'recomendacao-filmes-b3326',
    authDomain: 'recomendacao-filmes-b3326.firebaseapp.com',
    databaseURL: 'https://recomendacao-filmes-b3326-default-rtdb.firebaseio.com',
    storageBucket: 'recomendacao-filmes-b3326.firebasestorage.app',
    measurementId: 'G-3MRWFM1HV7',
  );
}
